
using { Gameplay.Stats }

# health and health_max live in Gameplay.Stats.Health.

mana<public>              := class<concrete>(stat_value){}
mana_max<public>          := class<concrete>(stat_value){}
mana_regen_rate<public>   := class<concrete>(stat_value){}
damage_multiplier<public> := class<concrete>(stat_value){}
damage_taken_mul<public>  := class<concrete>(stat_value){}
poison<public>            := class<concrete>(stat_value){}



